def run_all_tests():
    test_obiect()
    test_adauga_obiect()
    test_stergere_obiect()
    test_modificare_obiect()
    test_read()
    test_concatenare()
    test_lista_locatii_obiecte()
    test_pret_maxim_locatie()
    test_ordonare_obiecte()
